# Generated by Django 4.2.4 on 2023-08-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('time_since_change', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satellite_monitoring.satellites')),
            ],
        ),
    ]
