# Generated by Django 4.2.4 on 2023-08-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_monitoring', '0002_alter_satellites_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellites',
            name='time_since_change',
        ),
    ]
